<?php
// Automatically created cache file for the package format
// Do not modify this file

$CacheCodeDate = 1069339607;

$Parameters = array( "name" => "sevenx_extension",
                     "development" => false,
                     "summary" => "sevenx extension",
                     "description" => "sevenx extension",
                     "vendor" => "7x",
                     "vendor-dir" => "7x",
                     "priority" => false,
                     "type" => "extension",
                     "extension" => false,
                     "install_type" => "install",
                     "ezpublish" => array( "version" => "6.0.10-stable",
                                           "named-version" => "6.0" ),
                     "maintainers" => array(),
                     "packaging" => array( "timestamp" => "1705210212",
                                           "host" => "packages.se7enx.com",
                                           "packager" => false ),
                     "source" => false,
                     "documents" => array( array( "name" => "LICENCE",
                                                  "mime-type" => "text/plain",
                                                  "os" => "",
                                                  "data" => false,
                                                  "audience" => "" ) ),
                     "groups" => array(),
                     "changelog" => array(),
                     "file-list" => array(),
                     "simple-file-list" => array(),
                     "version-number" => "6.0",
                     "release-number" => "6.0.10-stable",
                     "release-timestamp" => false,
                     "licence" => "GPL",
                     "state" => "stable",
                     "dependencies" => array( "provides" => array(),
                                              "requires" => array(),
                                              "obsoletes" => array(),
                                              "conflicts" => array() ),
                     "install" => array( array( "type" => "ezextension",
                                                "name" => "",
                                                "os" => "",
                                                "filename" => "extension-ezwebin",
                                                "sub-directory" => "ezextension" ),
                                         array( "type" => "ezextension",
                                                "name" => "",
                                                "os" => "",
                                                "filename" => "extension-bcwebshop",
                                                "sub-directory" => "ezextension" ),
                                         array( "type" => "ezextension",
                                                "name" => "",
                                                "os" => "",
                                                "filename" => "extension-sevenx_themes_simple",
                                                "sub-directory" => "ezextension" ),
                                         array( "type" => "ezextension",
                                                "name" => "",
                                                "os" => "",
                                                "filename" => "extension-xrowmetadata",
                                                "sub-directory" => "ezextension" ) ),
                     "uninstall" => array( array( "type" => "ezextension",
                                                  "name" => "",
                                                  "os" => "",
                                                  "filename" => "extension-ezwebin",
                                                  "sub-directory" => "ezextension" ),
                                           array( "type" => "ezextension",
                                                  "name" => "",
                                                  "os" => "",
                                                  "filename" => "extension-bcwebshop",
                                                  "sub-directory" => "ezextension" ),
                                           array( "type" => "ezextension",
                                                  "name" => "",
                                                  "os" => "",
                                                  "filename" => "extension-sevenx_themes_simple",
                                                  "sub-directory" => "ezextension" ),
                                           array( "type" => "ezextension",
                                                  "name" => "",
                                                  "os" => "",
                                                  "filename" => "extension-xrowmetadata",
                                                  "sub-directory" => "ezextension" ) ) );
$InstallData = array();
$RepositoryPath = "var/storage/packages/7x";
?>
